### PR TITLE
Support secrets where multiple values are in a single secret in JSON …

### PR DESCRIPTION
**Pull request by nford**
…format

For cases where multiple key/value pairs are in a single secret in JSON format.

image

### CODE REVIEW

**Review by swilla — CHANGES_REQUESTED** [review]
You need a newline at the end of `src/LaravelAwsSecretsManager.php`.

**Comment by xingtianyoulong** [comment]
@swilla, could we merge this pull request? This issue is a very big bug because AWS Secret use JSON instead of name & value

**Comment by swilla** [comment]
> @swilla, could we merge this pull request? This issue is a very big bug because AWS Secret use JSON instead of name & value

We just need it to pass StyleCI first. Secrets Manager supports json, and single key-value entries.

**Comment by nford** [comment]
Sorry for the delay, new line added.

**Review by swilla — APPROVED** [review]

**Pull request merged**
