### PR TITLE
Support Laravel 11 and Use env() for dynamic configuration

### PR DESCRIPTION
**Pull request by shonggeok**

### CODE REVIEW

**Comment by swilla** [comment]
Can you fix StyleCI?

**Comment by shonggeok** [comment]
> Can you fix StyleCI?

Hi, could you please check again? Thanks!

**Review by swilla — CHANGES_REQUESTED** [review]
This looks good, can you update the readme with the dynamic config details and this will be ready to merge.

**Comment by shonggeok** [comment]
> This looks good, can you update the readme with the dynamic config details and this will be ready to merge.

Thanks for reviewing the changes. I've updated README with dynamic config details. Please review again!

**Review by swilla — APPROVED** [review]

**Pull request merged**
